<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NuGetAudit>false</NuGetAudit>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <AssemblyName>VisualFolderExplorer</AssemblyName>
    <RootNamespace>VisualFolderExplorer</RootNamespace>
    <ApplicationIcon></ApplicationIcon>
    <Version>1.0.2</Version>
    <FileVersion>1.0.2.0</FileVersion>
    <AssemblyVersion>1.0.2.0</AssemblyVersion>
  </PropertyGroup>
</Project>
